#!/usr/bin/env python3
"""
Digest email sender + HTML builder for yt-gem-daily (YouTube finance digest).

Extracted from yt-gem-daily.py to keep it importable. The infographic is
generated by digest_infographic.py (Gemini web image gen) from the video
verdicts and embedded inline (CID) at the conclusion of the email.
"""

import os
import re
import smtplib
import sys
from email.mime.image import MIMEImage
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import digest_infographic as infographic  # noqa: E402

SMTP_SERVER = "smtp.gmail.com"
SMTP_PORT = 465


def load_smtp() -> tuple[str, str, str]:
    user = (os.environ.get("SMTP_USER")
            or os.environ.get("YT_GEM_SMTP_USER", ""))
    pw = (os.environ.get("SMTP_PASS")
          or os.environ.get("YT_GEM_SMTP_PASS", ""))
    if not pw:
        try:
            with open(os.path.expanduser(
                    "~/.hermes/secrets/smtp_app_password.txt")) as f:
                pw = f.read().strip().replace(" ", "")
        except FileNotFoundError:
            pw = ""
    recipient = (os.environ.get("RECIPIENT")
                 or os.environ.get("YT_GEM_RECIPIENT", ""))
    return user, pw, recipient


_BULLET_RE = re.compile(r"^\s*[-*\u2022]\s+")
_NUM_RE = re.compile(r"^\s*\d+[.)]\s+")
_TABLE_SEP_RE = re.compile(r"^\|[\s:\-|]+\|$")


def _md_inline(s: str) -> str:
    s = re.sub(r"\*\*(.+?)\*\*", r"<b>\1</b>", s)
    s = re.sub(r"(?<!\*)\*([^*\n]+)\*(?!\*)", r"<i>\1</i>", s)
    s = re.sub(r"`([^`]+)`", r"<code>\1</code>", s)
    s = re.sub(r"\[([^\]]+)\]\((https?://[^)\s]+)\)",
               r'<a href="\2">\1</a>', s)
    return s


def md_to_html(text: str) -> str:
    """Small markdown renderer for analyst notes: headings, bullets, tables,
    bold/italic/code/links. Email-safe (escapes HTML first)."""
    import html as _html
    lines = _html.escape(text or "").split("\n")
    out: list[str] = []
    i = 0
    while i < len(lines):
        line = lines[i].rstrip()
        # table block: header row + separator row
        if (line.startswith("|") and i + 1 < len(lines)
                and _TABLE_SEP_RE.match(lines[i + 1].strip())):
            rows = []
            while i < len(lines) and lines[i].strip().startswith("|"):
                rows.append(lines[i].strip().strip("|").split("|"))
                i += 1
            head = "".join(f"<th>{_md_inline(c.strip())}</th>" for c in rows[0])
            body = "".join(
                "<tr>" + "".join(f"<td>{_md_inline(c.strip())}</td>" for c in r)
                + "</tr>" for r in rows[2:])
            out.append(f"<table><thead><tr>{head}</tr></thead>"
                       f"<tbody>{body}</tbody></table>")
            continue
        if re.match(r"^#{1,6}\s", line):
            lvl = min(len(line) - len(line.lstrip("#")), 4)
            out.append(f"<h{lvl+2}>{_md_inline(line.lstrip('#').strip())}</h{lvl+2}>")
        elif _BULLET_RE.match(line):
            items = []
            while i < len(lines) and _BULLET_RE.match(lines[i]):
                items.append(f"<li>{_md_inline(_BULLET_RE.sub('', lines[i].strip()))}</li>")
                i += 1
            out.append(f"<ul>{''.join(items)}</ul>")
            continue
        elif _NUM_RE.match(line):
            items = []
            while i < len(lines) and _NUM_RE.match(lines[i]):
                items.append(f"<li>{_md_inline(_NUM_RE.sub('', lines[i].strip()))}</li>")
                i += 1
            out.append(f"<ol>{''.join(items)}</ol>")
            continue
        elif line.strip() in ("---", "***"):
            out.append("<hr/>")
        elif not line.strip():
            pass
        else:
            out.append(f"<p>{_md_inline(line)}</p>")
        i += 1
    return "\n".join(out)


def build_html(date_str: str, results: list[dict], meta: dict) -> str:
    """results: [{channel,title,url,analysis,ok}] — full digest HTML."""
    ok = [r for r in results if r.get("ok")]
    cards = []
    for r in results:
        state = "✓" if r.get("ok") else "✗"
        analysis = r.get("analysis") or ""
        analysis = md_to_html(analysis)
        if not r.get("ok"):
            analysis = f"<i>{analysis}</i>"
        cards.append(f"""
  <div class="card">
    <div class="head">{state} 【{r.get('channel','')}】
      <a href="{r.get('url','')}">{r.get('title','')}</a></div>
    <div class="body">{analysis}</div>
  </div>""")
    summary = meta.get("digest_summary") or ""
    summary_html = ""
    if summary.strip():
        summary_html = f"""
  <div class="card summary">
    <div class="head">🧭 今日綜合研判 — 跨影片機構視角</div>
    <div class="body">{md_to_html(summary)}</div>
  </div>
  <hr/>"""
    css = """
  <style>
    body{font-family:-apple-system,'Segoe UI',Helvetica,Arial,sans-serif;
         color:#1f2328;max-width:820px;margin:0 auto;padding:16px;line-height:1.6;}
    h1{font-size:20px;border-bottom:2px solid #d0d7de;padding-bottom:8px;}
    .meta{color:#57606a;font-size:13px;}
    .card{border:1px solid #d0d7de;border-radius:10px;padding:12px 14px;
          margin:12px 0;}
    .card.summary{border:1px solid #1a7f37;background:#f2fbf4;}
    .card.summary .head{color:#1a7f37;}
    .head{font-weight:600;margin-bottom:6px;}
    a{color:#0969da;text-decoration:none;}
    .body{font-size:14px;}
    .body h2,.body h3,.body h4{font-size:15px;margin:14px 0 6px;}
    .body ul,.body ol{margin:6px 0 6px 18px;padding:0;}
    .body li{margin:3px 0;}
    .body p{margin:6px 0;}
    table{border-collapse:collapse;width:100%;margin:8px 0;font-size:13px;}
    th,td{border:1px solid #d0d7de;padding:5px 7px;text-align:left;
          vertical-align:top;}
    th{background:#f6f8fa;}
    code{background:#f6f8fa;padding:1px 4px;border-radius:4px;font-size:12px;}
    .infographic{width:100%;border-radius:10px;margin:10px 0 2px;}
    .cap{color:#57606a;font-size:12px;}
  </style>"""
    info_html = ""
    cids = meta.get("infographic_cids") or (
        [meta["infographic_cid"]] if meta.get("infographic_cid") else [])
    labels = ["方向分佈圖 — 由當日影片分析數據本地渲染（matplotlib）："
              "▲ 看多 · ▼ 看空 · ◆ 中性/事件",
              "市場脈搏儀表板 — Gemini NotebookLM 依 attached 影片來源生成"]
    if cids:
        info_html = "<h3>📌 今日重點一覽</h3>"
        for i, cid in enumerate(cids):
            info_html += (f"<img class='infographic' src='cid:{cid}' "
                          f"alt='digest infographic {i+1}'/>")
            if i < len(labels):
                info_html += f"<div class='cap'>{labels[i]}</div>"
    return f"""<html><head><meta charset="utf-8">{css}</head><body>
<h1>📊 財經頻道每日深度分析 — {date_str}</h1>
<div class="meta">分析引擎：Gemini Flash + Extended Thinking（webapi）
 | 影片：{len(ok)}/{len(results)} 成功 | {meta.get('channel_count','')} channels</div>
<hr/>
{summary_html}
{''.join(cards)}
<hr/>
{info_html}
<div class="meta">自動化摘要 — 內容僅供參考，非投資建議。</div>
</body></html>"""


def make_infographics(results: list[dict]) -> list[str]:
    """Conclusion infographics: (1) matplotlib data-viz pulse panel,
    (2) Gemini NotebookLM dashboard grounded in the video sources
    (dedicated daily notebook, YouTube links + takeaways attached)."""
    if infographic is None:
        return []
    out = []
    try:
        items = infographic.extract_verdicts_from_analyses(results)
        if not items:
            return out
        for it in items:
            it.setdefault("direction", infographic.verdict_direction(
                (it.get("verdict") or "") + " " + (it.get("title") or "")))
        # 1. matplotlib pulse panel
        img = infographic.render_videos_chart(items, title="財經影片今日重點")
        if img:
            out.append(img)
        # 2. NotebookLM infographic grounded in attached video sources
        try:
            from datetime import datetime as _dt
            nb_title = (f"Finance YouTube Daily Digest — "
                        f"{_dt.now().strftime('%Y-%m-%d')}")
            nb = infographic.nlm_ensure_notebook(nb_title)
            srcs = []
            for it in items[:6]:
                # find matching full analysis for content depth
                analysis = ""
                for r in results:
                    if r.get("ok") and r.get("title") == it.get("title"):
                        analysis = (r.get("analysis") or "")[:900]
                        break
                srcs.append({
                    "title": f"{it.get('channel','')}: "
                             f"{_shorten(it.get('title',''), 50)}",
                    "text": (f"Channel: {it.get('channel','')}\n"
                             f"Video title: {it.get('title','')}\n"
                             f"YouTube URL: {it.get('url','')}\n"
                             f"Video analysis (today):\n{analysis}")})
            n = infographic.nlm_add_text_sources(nb, srcs)
            print(f"[infographic] notebooklm: {n} sources attached", file=sys.stderr)
            inst = infographic.videos_notebook_context(
                items[:6], _dt.now().strftime("%Y-%m-%d"))
            url = infographic.nlm_generate_infographic(nb, inst)
            if url:
                img_path = infographic.nlm_download_image(
                    url, os.path.join(infographic.OUT_ROOT, "ytgem",
                                      f"nlm_{_dt.now().strftime('%Y%m%d-%H%M')}.png"))
                out.append(img_path)
        except Exception as e:  # noqa: BLE001
            print(f"[infographic] notebooklm failed (continues): {e}",
                  file=sys.stderr)
    except Exception as e:  # noqa: BLE001
        print(f"[infographic] partial failure: {e}", file=sys.stderr)
    return out


def _shorten(s: str, n: int) -> str:
    import re as _re
    s = _re.sub(r"\s+", " ", s or "").strip()
    return s if len(s) <= n else s[: n - 1].rstrip(" ,;:.—-") + "…"


def make_infographic(results: list[dict]) -> str | None:
    """Back-compat single-image wrapper."""
    imgs = make_infographics(results)
    return imgs[0] if imgs else None


def send_html(subject: str, html: str,
              image_paths: list[str] | str | None = None,
              cids: list[str] | None = None) -> bool:
    try:
        with open("/tmp/yt_digest_email.html", "w") as f:
            f.write(html)
    except Exception:
        pass
    if os.environ.get("DIGEST_DRY_RUN", "").lower() in ("1", "true", "yes"):
        print(f"DRY RUN — email suppressed (would send: {subject})")
        return True
    user, pw, recipient = load_smtp()
    if not user or not pw or not recipient:
        print("ERROR: SMTP not configured", file=sys.stderr)
        return False
    if isinstance(image_paths, str):
        image_paths = [image_paths]
    image_paths = image_paths or []
    cids = cids or [f"infographic{i}" for i in range(len(image_paths))]
    if image_paths:
        alt = MIMEMultipart("alternative")
        alt.attach(MIMEText("HTML 郵件 — 請啟用 HTML 顯示。", "plain", "utf-8"))
        alt.attach(MIMEText(html, "html", "utf-8"))
        msg = MIMEMultipart("related")
        msg.attach(alt)
        for i, ip in enumerate(image_paths):
            if not ip or not os.path.exists(ip):
                continue
            with open(ip, "rb") as fh:
                img = MIMEImage(fh.read())
            cid = cids[i] if i < len(cids) else f"infographic{i}"
            img.add_header("Content-ID", f"<{cid}>")
            img.add_header("Content-Disposition", "inline",
                           filename=os.path.basename(ip))
            msg.attach(img)
    else:
        msg = MIMEMultipart("alternative")
        alt = MIMEMultipart("alternative")
        alt.attach(MIMEText("HTML 郵件 — 請啟用 HTML 顯示。", "plain", "utf-8"))
        alt.attach(MIMEText(html, "html", "utf-8"))
        msg.attach(alt)
    msg["Subject"] = subject
    msg["From"] = user
    msg["To"] = recipient
    try:
        server = smtplib.SMTP_SSL(SMTP_SERVER, SMTP_PORT, timeout=30)
        server.login(user, pw)
        server.sendmail(user, [recipient], msg.as_string())
        server.quit()
        return True
    except Exception as e:  # noqa: BLE001
        print(f"ERROR: send failed: {e}", file=sys.stderr)
        return False
