#!/usr/bin/env python3
"""
Digest email sender + HTML builder for yt-gem-daily (YouTube finance digest).

Extracted from yt-gem-daily.py to keep it importable. The infographic is
generated by digest_infographic.py (Gemini web image gen) from the video
verdicts and embedded inline (CID) at the conclusion of the email.
"""

import os
import re
import smtplib
import sys
from email.mime.image import MIMEImage
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import digest_infographic as infographic  # noqa: E402

SMTP_SERVER = "smtp.gmail.com"
SMTP_PORT = 465


def load_smtp() -> tuple[str, str, str]:
    user = os.environ.get("SMTP_USER", "ppoppo2051@gmail.com")
    pw = os.environ.get("SMTP_PASS", "")
    if not pw:
        try:
            with open(os.path.expanduser(
                    "~/.hermes/secrets/smtp_app_password.txt")) as f:
                pw = f.read().strip().replace(" ", "")
        except FileNotFoundError:
            pw = ""
    recipient = os.environ.get("RECIPIENT", "cyc236ha@gmail.com")
    return user, pw, recipient


def build_html(date_str: str, results: list[dict], meta: dict) -> str:
    """results: [{channel,title,url,analysis,ok}] — full digest HTML."""
    ok = [r for r in results if r.get("ok")]
    cards = []
    for r in results:
        state = "✓" if r.get("ok") else "✗"
        analysis = r.get("analysis") or ""
        analysis = analysis if r.get("ok") else \
            f"<i>{analysis}</i>"
        # crude markdown->html for analysis text
        analysis = re.sub(r"\*\*(.+?)\*\*", r"<b>\1</b>", analysis)
        analysis = re.sub(r"^#+\s*(.+)$", r"<h4>\1</h4>", analysis, flags=re.M)
        analysis = analysis.replace("\n", "<br/>")
        cards.append(f"""
  <div class="card">
    <div class="head">{state} 【{r.get('channel','')}】
      <a href="{r.get('url','')}">{r.get('title','')}</a></div>
    <div class="body">{analysis}</div>
  </div>""")
    css = """
  <style>
    body{font-family:-apple-system,'Segoe UI',Helvetica,Arial,sans-serif;
         color:#1f2328;max-width:780px;margin:0 auto;padding:16px;line-height:1.6;}
    h1{font-size:20px;border-bottom:2px solid #d0d7de;padding-bottom:8px;}
    .meta{color:#57606a;font-size:13px;}
    .card{border:1px solid #d0d7de;border-radius:10px;padding:12px 14px;
          margin:12px 0;}
    .head{font-weight:600;margin-bottom:6px;}
    a{color:#0969da;text-decoration:none;}
    .body{font-size:14px;}
    .infographic{width:100%;border-radius:10px;margin:10px 0 2px;}
    .cap{color:#57606a;font-size:12px;}
  </style>"""
    info_html = ""
    cids = meta.get("infographic_cids") or (
        [meta["infographic_cid"]] if meta.get("infographic_cid") else [])
    labels = ["方向分佈圖 — 由當日影片分析數據本地渲染（matplotlib）："
              "▲ 看多 · ▼ 看空 · ◆ 中性/事件",
              "市場脈搏儀表板 — Gemini NotebookLM 依 attached 影片來源生成"]
    if cids:
        info_html = "<h3>📌 今日重點一覽</h3>"
        for i, cid in enumerate(cids):
            info_html += (f"<img class='infographic' src='cid:{cid}' "
                          f"alt='digest infographic {i+1}'/>")
            if i < len(labels):
                info_html += f"<div class='cap'>{labels[i]}</div>"
    return f"""<html><head><meta charset="utf-8">{css}</head><body>
<h1>📊 財經頻道每日深度分析 — {date_str}</h1>
<div class="meta">分析引擎：Gemini Flash + Extended Thinking（webapi）
 | 影片：{len(ok)}/{len(results)} 成功 | {meta.get('channel_count','')} channels</div>
<hr/>
{''.join(cards)}
<hr/>
{info_html}
<div class="meta">自動化摘要 — 內容僅供參考，非投資建議。</div>
</body></html>"""


def make_infographics(results: list[dict]) -> list[str]:
    """Conclusion infographics: (1) matplotlib data-viz pulse panel,
    (2) Gemini NotebookLM dashboard grounded in the video sources
    (dedicated daily notebook, YouTube links + takeaways attached)."""
    if infographic is None:
        return []
    out = []
    try:
        items = infographic.extract_verdicts_from_analyses(results)
        if not items:
            return out
        for it in items:
            it.setdefault("direction", infographic.verdict_direction(
                (it.get("verdict") or "") + " " + (it.get("title") or "")))
        # 1. matplotlib pulse panel
        img = infographic.render_videos_chart(items, title="財經影片今日重點")
        if img:
            out.append(img)
        # 2. NotebookLM infographic grounded in attached video sources
        try:
            from datetime import datetime as _dt
            nb_title = (f"Finance YouTube Daily Digest — "
                        f"{_dt.now().strftime('%Y-%m-%d')}")
            nb = infographic.nlm_ensure_notebook(nb_title)
            srcs = [{"title": f"{it.get('channel','')}: "
                               f"{_shorten(it.get('title',''), 50)}",
                     "url": it["url"]}
                    for it in items if it.get("url")]
            n = infographic.nlm_add_youtube_sources(nb, srcs[:6])
            print(f"[infographic] notebooklm: {n} sources attached", file=sys.stderr)
            inst = infographic.videos_notebook_context(
                items[:6], _dt.now().strftime("%Y-%m-%d"))
            url = infographic.nlm_generate_infographic(nb, inst)
            if url:
                img_path = infographic.nlm_download_image(
                    url, os.path.join(infographic.OUT_ROOT, "ytgem",
                                      f"nlm_{_dt.now().strftime('%Y%m%d-%H%M')}.png"))
                out.append(img_path)
        except Exception as e:  # noqa: BLE001
            print(f"[infographic] notebooklm failed (continues): {e}",
                  file=sys.stderr)
    except Exception as e:  # noqa: BLE001
        print(f"[infographic] partial failure: {e}", file=sys.stderr)
    return out


def _shorten(s: str, n: int) -> str:
    import re as _re
    s = _re.sub(r"\s+", " ", s or "").strip()
    return s if len(s) <= n else s[: n - 1].rstrip(" ,;:.—-") + "…"


def make_infographic(results: list[dict]) -> str | None:
    """Back-compat single-image wrapper."""
    imgs = make_infographics(results)
    return imgs[0] if imgs else None


def send_html(subject: str, html: str,
              image_paths: list[str] | str | None = None,
              cids: list[str] | None = None) -> bool:
    user, pw, recipient = load_smtp()
    if not user or not pw or not recipient:
        print("ERROR: SMTP not configured", file=sys.stderr)
        return False
    if isinstance(image_paths, str):
        image_paths = [image_paths]
    image_paths = image_paths or []
    cids = cids or [f"infographic{i}" for i in range(len(image_paths))]
    if image_paths:
        alt = MIMEMultipart("alternative")
        alt.attach(MIMEText("HTML 郵件 — 請啟用 HTML 顯示。", "plain", "utf-8"))
        alt.attach(MIMEText(html, "html", "utf-8"))
        msg = MIMEMultipart("related")
        msg.attach(alt)
        for i, ip in enumerate(image_paths):
            if not ip or not os.path.exists(ip):
                continue
            with open(ip, "rb") as fh:
                img = MIMEImage(fh.read())
            cid = cids[i] if i < len(cids) else f"infographic{i}"
            img.add_header("Content-ID", f"<{cid}>")
            img.add_header("Content-Disposition", "inline",
                           filename=os.path.basename(ip))
            msg.attach(img)
    else:
        msg = MIMEMultipart("alternative")
        alt = MIMEMultipart("alternative")
        alt.attach(MIMEText("HTML 郵件 — 請啟用 HTML 顯示。", "plain", "utf-8"))
        alt.attach(MIMEText(html, "html", "utf-8"))
        msg.attach(alt)
    msg["Subject"] = subject
    msg["From"] = user
    msg["To"] = recipient
    try:
        server = smtplib.SMTP_SSL(SMTP_SERVER, SMTP_PORT, timeout=30)
        server.login(user, pw)
        server.sendmail(user, [recipient], msg.as_string())
        server.quit()
        return True
    except Exception as e:  # noqa: BLE001
        print(f"ERROR: send failed: {e}", file=sys.stderr)
        return False
