#!/usr/bin/env python3
"""
Digest email sender + HTML builder for yt-gem-daily (YouTube finance digest).

Extracted from yt-gem-daily.py to keep it importable. The infographic is
generated by digest_infographic.py (Gemini web image gen) from the video
verdicts and embedded inline (CID) at the conclusion of the email.
"""

import os
import re
import smtplib
import sys
from email.mime.image import MIMEImage
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import digest_infographic as infographic  # noqa: E402

SMTP_SERVER = "smtp.gmail.com"
SMTP_PORT = 465


def load_smtp() -> tuple[str, str, str]:
    user = os.environ.get("SMTP_USER", "ppoppo2051@gmail.com")
    pw = os.environ.get("SMTP_PASS", "")
    if not pw:
        try:
            with open(os.path.expanduser(
                    "~/.hermes/secrets/smtp_app_password.txt")) as f:
                pw = f.read().strip().replace(" ", "")
        except FileNotFoundError:
            pw = ""
    recipient = os.environ.get("RECIPIENT", "cyc236ha@gmail.com")
    return user, pw, recipient


def build_html(date_str: str, results: list[dict], meta: dict) -> str:
    """results: [{channel,title,url,analysis,ok}] — full digest HTML."""
    ok = [r for r in results if r.get("ok")]
    cards = []
    for r in results:
        state = "✓" if r.get("ok") else "✗"
        analysis = r.get("analysis") or ""
        analysis = analysis if r.get("ok") else \
            f"<i>{analysis}</i>"
        # crude markdown->html for analysis text
        analysis = re.sub(r"\*\*(.+?)\*\*", r"<b>\1</b>", analysis)
        analysis = re.sub(r"^#+\s*(.+)$", r"<h4>\1</h4>", analysis, flags=re.M)
        analysis = analysis.replace("\n", "<br/>")
        cards.append(f"""
  <div class="card">
    <div class="head">{state} 【{r.get('channel','')}】
      <a href="{r.get('url','')}">{r.get('title','')}</a></div>
    <div class="body">{analysis}</div>
  </div>""")
    css = """
  <style>
    body{font-family:-apple-system,'Segoe UI',Helvetica,Arial,sans-serif;
         color:#1f2328;max-width:780px;margin:0 auto;padding:16px;line-height:1.6;}
    h1{font-size:20px;border-bottom:2px solid #d0d7de;padding-bottom:8px;}
    .meta{color:#57606a;font-size:13px;}
    .card{border:1px solid #d0d7de;border-radius:10px;padding:12px 14px;
          margin:12px 0;}
    .head{font-weight:600;margin-bottom:6px;}
    a{color:#0969da;text-decoration:none;}
    .body{font-size:14px;}
    .infographic{width:100%;border-radius:10px;margin:10px 0 2px;}
    .cap{color:#57606a;font-size:12px;}
  </style>"""
    info_html = ""
    if meta.get("infographic_cid"):
        info_html = ("<h3>📌 今日重點一覽</h3>"
                     f"<img class='infographic' src='cid:{meta['infographic_cid']}' "
                     f"alt='digest infographic'/>"
                     "<div class='cap'>圖表由 Gemini 圖像生成（web）產生。</div>")
    return f"""<html><head><meta charset="utf-8">{css}</head><body>
<h1>📊 財經頻道每日深度分析 — {date_str}</h1>
<div class="meta">分析引擎：Gemini Flash + Extended Thinking（webapi）
 | 影片：{len(ok)}/{len(results)} 成功 | {meta.get('channel_count','')} channels</div>
<hr/>
{''.join(cards)}
<hr/>
{info_html}
<div class="meta">自動化摘要 — 內容僅供參考，非投資建議。</div>
</body></html>"""


def make_infographic(results: list[dict]) -> str | None:
    """Conclusion infographic. Primary: matplotlib data-viz (sentiment split
    bar + direction-marked takeaways). Fallback: Gemini image gen."""
    if infographic is None:
        return None
    try:
        items = infographic.extract_verdicts_from_analyses(results)
        if not items:
            return None
        img = infographic.render_videos_chart(
            items, title="財經影片今日重點")
        if img:
            return img
        if not infographic.matplotlib_available():
            prompt = infographic.build_videos_prompt("財經影片今日重點", items)
            if prompt:
                return infographic.gen_image(
                    prompt, os.path.join(infographic.OUT_ROOT, "ytgem"))
        return None
    except Exception as e:  # noqa: BLE001
        print(f"[infographic] skipped: {e}", file=sys.stderr)
        return None


def send_html(subject: str, html: str, image_path: str | None = None,
              cid: str = "infographic") -> bool:
    user, pw, recipient = load_smtp()
    if not user or not pw or not recipient:
        print("ERROR: SMTP not configured", file=sys.stderr)
        return False
    if image_path and os.path.exists(image_path):
        alt = MIMEMultipart("alternative")
        alt.attach(MIMEText("HTML 郵件 — 請啟用 HTML 顯示。", "plain", "utf-8"))
        alt.attach(MIMEText(html, "html", "utf-8"))
        msg = MIMEMultipart("related")
        msg.attach(alt)
        with open(image_path, "rb") as fh:
            img = MIMEImage(fh.read())
        img.add_header("Content-ID", f"<{cid}>")
        img.add_header("Content-Disposition", "inline",
                       filename=os.path.basename(image_path))
        msg.attach(img)
    else:
        msg = MIMEMultipart("alternative")
        alt = MIMEMultipart("alternative")
        alt.attach(MIMEText("HTML 郵件 — 請啟用 HTML 顯示。", "plain", "utf-8"))
        alt.attach(MIMEText(html, "html", "utf-8"))
        msg.attach(alt)
    msg["Subject"] = subject
    msg["From"] = user
    msg["To"] = recipient
    try:
        server = smtplib.SMTP_SSL(SMTP_SERVER, SMTP_PORT, timeout=30)
        server.login(user, pw)
        server.sendmail(user, [recipient], msg.as_string())
        server.quit()
        return True
    except Exception as e:  # noqa: BLE001
        print(f"ERROR: send failed: {e}", file=sys.stderr)
        return False
